#Functions:
my_lst = [1,2,3,4,5,6,7,8,9,12,23,34,56,68,89,34,56,78]
# len(list_variable)
print(len(my_lst))
# max(list_variable)
print(max(my_lst))
# min(list_variable)
print(min(my_lst))
# sum(list_variable)
print(sum(my_lst))
# sorted(list_variable)
print(sorted(my_lst))
# list(list_variable)
name = "Ankith","Rakshita","Gagana","Bharath","Adarsh","Muthu"
char_lst = list(name)
print(char_lst)
# any(list_variable)
my_lst = ["",1]
print(any(my_lst))
# all(list_variable)
print(all(my_lst))

# Methods:
your_list = [10,20,30,40,50,60,70,80,90]
# .append(object)
your_list.append(97)
print(your_list)
# .insert(index,object)
your_list.insert(3,99)
print(your_list)
# .remove(object)
your_list.remove(99)
print(your_list)
# .pop([index])
your_list.pop()
print(your_list)
your_list.pop(0)
print(your_list)
your_list.pop()
print(your_list)
# .index(object)
your_list.append(90)
your_list.append(180)
your_list.append(280)
your_list.append(380)
your_list.append(80)
print(your_list)
print(your_list.index(80))
print(your_list.index(80,7))
# .count(object)
print(your_list.count(80))
print(your_list.count(20))
# .sort()
# .reverse()
# .clear()
your_list.clear()
print(your_list)
